---
title: "PHS_project_02"
author: "Jonny Nelson"
date: "02/01/2022"
output: html_document
---

```{r}
library(janitor)
library(tidyverse)
library(lubridate)
library(tsibbledata)
library(tsibble)
library(fable)
library(slider)
library(feasts)
library(tidyquant)
library(sf)
library(rgdal)

ae <- read_csv("monthly_ae_waitingtimes_202110.csv")

nhs_boards <- read_csv("PHS_a_and_e_health_board_keys.csv")

ae_clean <- ae %>%
  clean_names() %>%
  mutate(date = ym(month),
         date_01 = as.Date(month, format = "%Y-%m"))


glimpse(ae)

unique(ae$Month)

# Month is YearMonth format (dbl)

unique(ae$Country)

# Scotland

# TreakmentLocation == NHS Hospital

unique(ae$DepartmentType) 

# "Minor Injury Unit or Other" "Emergency Department" 

# Number of Attendances

head(ae, 100)

# NumberOfAttendancesAggregate split by health board, department type

# AttendanceGreater8/12 Hours - number

unique(ae_clean$number_of_attendances_aggregate)
```

# Histogram of Admissions

```{r}
ae_clean %>%
  select(date, number_of_attendances_aggregate, department_type) %>%
  filter(date >= "2017-07-01") %>%
  group_split(date) %>%
  mutate(
    moving_avg = slide_dbl(
      .x = number_of_attendances_aggregate, 
      .f = ~ mean(., na.rm = TRUE),
      .before = 100,
      .after = 100
    )
  ) %>%
  ungroup()%>%
  ggplot(aes(x = date, y = number_of_attendances_aggregate)) +
  geom_col(aes(x = date, y =  number_of_attendances_aggregate, fill = department_type)) +
  geom_ma(ma_fun = SMA, n = 30, colour = "red") +
  ggtitle("Time Series for Number of Attendances") +
  labs(x = "Date", y = "Number of Attendances")

# Need to get the moving average to work
```

# Getting the moving average to work

```{r}
ae_clean %>%
  select(date, number_of_attendances_aggregate, department_type) %>%
  filter(date >= "2017-07-01") %>%
  mutate(
    moving_avg = slide_dbl(
      .x = number_of_attendances_aggregate, 
      .f = ~ mean(., na.rm = TRUE),
      .before = 100,
      .after = 100
    )
  ) %>%
  ggplot() +
  geom_col(aes(x = date, y =  number_of_attendances_aggregate, fill = department_type)) +
  ggtitle("Time Series for Number of Attendances") +
  labs(x = "Date", y = "Number of Attendances")

# Need to get the moving average to work
```
# Transforming data into per year basis

```{r}
ae_clean %>%
  select(date, number_of_attendances_aggregate, department_type, hbt) %>%
  filter(date >= "2017-07-01") %>%
  mutate(
    moving_avg = slide_dbl(
      .x = number_of_attendances_aggregate, 
      .f = ~ mean(., na.rm = TRUE),
      .before = 100,
      .after = 100
    )
  ) %>%
  ggplot() +
  geom_col(aes(x = date, y =  number_of_attendances_aggregate, fill = department_type)) +
  ggtitle("Time Series for Number of Attendances") +
  labs(x = "Date", y = "Number of Attendances")
```

# Number of Attendances by HBT

```{r}
ae_clean %>%
  select(date, number_of_attendances_aggregate, department_type, hbt) %>%
  filter(date >= "2017-07-01") %>%
  mutate(
    moving_avg = slide_dbl(
      .x = number_of_attendances_aggregate, 
      .f = ~ mean(., na.rm = TRUE),
      .before = 100,
      .after = 100
    )
  ) %>%
  ggplot() +
  geom_col(aes(x = date, y =  number_of_attendances_aggregate, fill = hbt)) +
  ggtitle("Time Series for Number of Attendances") +
  labs(x = "Date", y = "Number of Attendances")
```

# Attendances over 8 & 12 hours

```{r}
ae_clean %>%
  select(date, attendance_greater8hrs, department_type, hbt) %>%
  filter(date >= "2017-07-01") %>%
  ggplot() +
  geom_col(aes(x = date, y =  attendance_greater8hrs, fill = hbt)) +
  ggtitle("Time Series for Number of Attendances") +
  labs(x = "Date", y = "Number of Attendances")
```


# Transforming the tibble to a tsibble

```{r}
ae_clean %>%
  group_by(date) %>%
  tsibble()

ae_squish <- ae_clean %>%
  mutate(month = month(date, label = TRUE, abbr = FALSE)) %>%
  group_by(date) %>%
  summarise(number_of_attendances = sum(number_of_attendances_aggregate)) %>%
  tsibble() 

ae_squish %>%
  gg_season()
```

## To Do List

### - Clean the data fully (Date)
### - Wrangle the data to spot trends and patterns
### - Plot Spatial Map










# Spatial Map

```{r}
library(sf)
library(rgdal)
library(raster)
library(ggplot2)
library(rgeos)
library(mapview)
library(leaflet)
library(broom) # if you plot with ggplot and need to turn sp data into dataframes
options(stringsAsFactors = FALSE)

# Code Chunk did not work

# healthboard_shapefile <- readOGR(dsn = "NHS_healthboard_shapefiles_simple/",
#                                  layer = "NHS_HealthBoards_2019",
#                                  GDAL1_integer64_policy = TRUE)

shapes <- read_sf(dsn = "NHS_healthboard_shapefiles_simple/SG_NHS_HealthBoards_2019", layer = "SG_NHS_HealthBoards_2019")

```


