---
title: "RStudio Lab"
output: html_notebook
---

# Question 1

```{r}
state_income_data_practice <- read_csv("state_income_data.csv")
```


```{r}
dim(state_income_data_practice)

# 51 Observations and 16 Columns
```

```{r}
state_income_data_practice
```

# Variable names are Index (character), State #(character) and Y2002 - Y2015 (numeric)

# Question 2 

```{r}
select(state_income_data, Index, State, Y2002:Y2008)
```

# Question 3

```{r}
rename(state_income_data_practice, Index ==  "first_letter")
```

# Question 4

```{r}
states_ABC <- filter(state_income_data_practice, Index %in% c("A", "B", "C"))

states_ABC
```

# Question 5

```{r}
select(states_ABC, Y2008, State, Index) %>%
  arrange(desc(Y2008))
```

# Question 6 and 7

```{r}
where_income_change_500000 <- mutate(states_ABC, income_change = Y2008 - Y2002) %>%
  group_by(income_change > 500000) %>%
  pull()

where_income_change_500000
```

# Question 8 - Calculate the mean and median income change for all seven states.

```{r}
states_ABC %>%
  mutate(sum_values = Y2002+Y2003+Y2004+Y2005+Y2006+Y2007+Y2008+Y2009+Y2010+Y2011+Y2012+Y2013+Y2014+Y2015) %>%
  mutate(mean = sum_values/14) %>%
  mutate(median = median())

```

#Question 9 

```{r}
state_income_data_practice %>%
  select(State, Y2008) %>%
  arrange(desc(Y2008)) %>%
  filter(Y2008 > 1000000) %>%
  head(10)

  
```

