---
title: "workshop_day03"
author: "Jonny Nelson"
date: "26/01/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(cluster)
library(factoextra)
library(dendextend)
library(corrplot)

edu_data <- read_csv("2_hierarchical_clustering/data/school_data.csv")

head(edu_data)
```

```{r}
edu_data <- edu_data %>%
  column_to_rownames("X1")

# it becomes row names
```

```{r}
edu_data_scale <- edu_data %>%
  mutate(across(where(is.numeric), scale))

# Normalised data
```

```{r}
edu_data_scale %>%
  pivot_longer(cols = everything(),
               names_to = "type", 
               values_to = "value") %>% #convert data to long format
  group_by(type) %>%
  summarise(mean = round(mean(value)), 
            sd = sd(value))
```

```{r}
corrplot(cor(edu_data_scale), method = "number", type = "lower")
```

```{r}
diss_matrix <- edu_data_scale %>%
  select(home_school) %>%
  dist(method = "euclidean")
```

```{r}
fviz_dist(diss_matrix)
```

```{r}
clusters <- diss_matrix %>%
  hclust(method = "complete")
```

```{r}
clusters %>%
  plot(cex = 0.6,
       hang = -5)
```

```{r}
alt_clusters <- diss_matrix %>%
  hclust(method = "ward.D2")
```

```{r}
clustering_dendrogram <- clusters %>%
  as.dendrogram() %>%
  dendextend::set("labels_cex", 0.5)
```

```{r}
alt_clustering_dendrogram <- alt_clusters %>%
  as.dendrogram() %>%
  dendextend::set("labels_cex", 0.6)
```

```{r}
dend_diff(clustering_dendrogram, alt_clustering_dendrogram)
```

```{r}
plot(clusters, cex = 0.6, hang = -1)
```

```{r}
plot(clusters, cex = 0.6, hang = -1)
rect.hclust(clusters, k = 10, border = 2:5)

# k = number of clusters
# border = colours used to show clusters
```

```{r}
edu_clustered_h2 <- edu_data %>%
  mutate(school_cluster = cutree(clusters, k = 2))
```

```{r}
edu_data %>% 
  rownames_to_column('state') %>% 
  mutate(school_cluster = cutree(clusters, 5)) %>% 
  ggplot(aes(home_school, state_school, colour = factor(school_cluster))) +
  geom_point() +
  geom_text(aes(label = state), check_overlap = T, size = 3,
            hjust = 'inward', vjust = 'inward') +
  guides(colour = 'none')
```

## Taskles

```{r}
diss_matrix_02 <- edu_data_scale %>%
  select(private_school) %>%
  dist(method = "euclidean")

clusters_02 <- diss_matrix_02 %>%
  hclust(method = "complete")
```

```{r}
clusters_02 %>%
  plot(cex = 0.6,
       hang = -5)
```

```{r}
alt_clusters_02 <- diss_matrix_02 %>%
  hclust(method = "ward.D2")
```

```{r}
clustering_dendrogram_02 <- clusters_02 %>%
  as.dendrogram() %>%
  dendextend::set("labels_cex", 0.5)
```

```{r}
alt_clustering_dendrogram_02 <- alt_clusters_02 %>%
  as.dendrogram() %>%
  dendextend::set("labels_cex", 0.6)
```

```{r}
dend_diff(clustering_dendrogram_02, alt_clustering_dendrogram_02)
```

```{r}
plot(clusters_02, cex = 0.6, hang = -1)
```

```{r}
plot(clusters_02, cex = 0.6, hang = -1)
rect.hclust(clusters_02, k = 10, border = 2:5)

# k = number of clusters
# border = colours used to show clusters
```

```{r}
edu_clustered_h2_02 <- edu_data %>%
  mutate(school_cluster = cutree(clusters, k = 2))
```


# K Mean Clustering


```{r}
head(edu_data)
```

```{r}
library(janitor)

edu_data
```

```{r}
edu_data <- edu_data %>%
  select(home_school, state_school)
```

```{r}
ggplot(edu_data) +
  geom_point(aes(x = home_school, y = state_school))
```

```{r}
edu_data %>%
  as_tibble() %>%
  pivot_longer(cols = c(home_school, state_school), 
               names_to = "type", 
               values_to = "value") %>% #convert data to long format
  group_by(type)%>%
  summarise(mean = round(mean(value)), 
            sd = sd(value))
```

```{r}
edu_data_scale <- edu_data %>%
 mutate(across(where(is.numeric), scale))
```

```{r}
set.seed(1234)  

clustered_edu <- kmeans(edu_data_scale,
                        centers = 6,
                        nstart = 25)

# centres = number of clusters
# nstart = number of times run
```

```{r}
library(broom)

broom::tidy(clustered_edu,
            col.names = colnames(edu_data_scale))

broom::augment(clustered_edu, edu_data_scale)
```

```{r}
library(purrr) 

max_k <- 20
k_clusters <- tibble(k = 1:max_k) %>%
  mutate(
    kclust = map(k, ~ kmeans(edu_scale, .x, nstart = 25)),
    tidied = map(kclust, tidy),
    glanced = map(kclust, glance),
    augmented = map(kclust, augment, edu_data)
  )

k_clusters
```
## Metrics: Sum of Squares

```{r}
# big object
object.size(k_clusters) 
```

```{r}
clusterings <- k_clusters %>%
  unnest(glanced)
```

```{r}
ggplot(clusterings, aes(x=k, y=tot.withinss)) +
  geom_point() +
    geom_line() +
    scale_x_continuous(breaks = seq(1, 20, by = 1))
```

```{r}
library(factoextra)

fviz_nbclust(edu_data_scale,
             kmeans,
             method = "silhouette",
             nstart = 25)
```

```{r}
fviz_nbclust(edu_scale, 
             kmeans, 
             method = "gap_stat", 
             nstart = 25, 
             k.max = 10)
```


```{r}
 clusterings %>% 
  unnest(cols = c(augmented)) %>%
  filter(k <= 6) %>%
  ggplot(aes(x = home_school, y = state_school)) +
  geom_point(aes(color = .cluster))

# Clusters plotted out
```

```{r}
clusterings %>% 
  unnest(cols = c(augmented)) %>%
  filter(k == 2) %>%
 ggplot(aes(x = home_school, y = state_school, colour = .cluster, label = .rownames)) +
  geom_point(aes(color = .cluster)) +
  geom_text(hjust = 0, vjust = - 0.5, size = 3)

# Clustering plot with hierarchical clustering, 
```


# Lab 

## Normalised and Cleaned Data

```{r}
library(CodeClanData)

# Summary of students_clean shows no NA values

students_clean <- students_big %>%
  select(contains("importance")) %>%
  mutate(across(where(is.numeric), scale))
```

## Making the Clusters

```{r}
set.seed(9)  

clustered_students <- kmeans(students_clean,
                             centers = 6,
                             nstart = 25)

# centres = number of clusters
# nstart = number of times run
```

```{r}
library(purrr) 

max_k <- 20
k_clusterz <- tibble(k = 1:max_k) %>%
  mutate(
    kclust = map(k, ~ kmeans(students_clean, .x, nstart = 25)),
    tidied = map(kclust, tidy),
    glanced = map(kclust, glance),
    augmented = map(kclust, augment, edu_data)
  )

k_clusterz
```

```{r}
clusteringz <- k_clusterz %>%
  unnest(glanced)
```

```{r}
ggplot(clusteringz, aes(x=k, y=tot.withinss)) +
  geom_point() +
    geom_line() +
    scale_x_continuous(breaks = seq(1, 20, by = 1))
```

```{r}
library(factoextra)

fviz_nbclust(students_clean,
             kmeans,
             method = "silhouette",
             nstart = 25)
```

```{r}
fviz_nbclust(students_clean, 
             kmeans, 
             method = "gap_stat", 
             nstart = 25, 
             k.max = 10)
```

## Part B (I)

### Removing the unwanted variables 

```{r}
students_env <- students_clean %>%
  select(-c(importance_owning_computer, importance_internet_access))
```

### Making Clustors

```{r}
set.seed(9)  

clustered_students_env <- kmeans(students_env,
                                 centers = 2,
                                 nstart = 25)

# centres = number of clusters
# nstart = number of times run
```

```{r}
dist_matrix <- students_env %>%
  dist(method = "euclidean")
```

```{r}
fviz_dist(dist_matrix)
```

```{r}
clusterz <- dist_matrix %>%
  hclust(method = "complete")
```

```{r}
clusterz %>%
  plot(cex = 0.6,
       hang = -5)
```

```{r}
plot(clusterz, cex = 0.6, hang = -1)
rect.hclust(clusterz, k = 2, border = 2:5)

# k = number of clusters
# border = colours used to show clusters
```

```{r}
library(GGally)

students_env_2clusters <- students_env %>%
  mutate(school_cluster = cutree(clusterz, k = 2)) 

students_env_2clusters %>%
  ggplot(aes(x = importance_reducing_pollution,
             y = importance_saving_enery)) +
  geom_point(aes(color = school_cluster))

```

```{r}
corrplot(cor(students_clean), method = "number", type = "lower")
# Importance in internet access and owning computer = 0.86
```

