---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
customers <- tibble(
  customer_ID = c(001, 002, 004, 005, 008, 010), 
  name = c("John Smith", "Jane Adams", "Robert Landry", "Jane Tow", "Raul Tann", "Hilary Joyal"),
  email_address = c("johnsmith@gmail.com", "janea@gmail.com", "rlabdry@hotmail.com", "janet89@aol.com", "paul.tann1@gmail.com", NA),
  shipping_address = c("32 Station Road, Edinburgh", "42 Park Drive, Edinburgh", NA, "10 Gardiner Rd, Edinburgh", "12 Main St, Edinburgh", " 234 Queensferry Rd, Edinburgh,")
)

customers
```

```{r}
orders <- tibble(
  customer_ID = c(001, 002, 005, 010, 012, 001), 
  order_number = c("KU65781", "SU98201", "JS76821", "YR28212", "JS91221","YR21873"),
  order_total = c("£32.50", "£56.00", "£100.02", "£20.25", "£39.50", "£45.00"),
  product_code = c("XZY780", "XYZ123", "XYZ256", "XYZ262", "XYZ345", "XYZ127")
)

orders

```

```{r}

inner_join(customers, orders, "customer_ID")

# variable has to be found in the left and the right data frame

# Joining by customer_ID

```

```{r}

left_join(customers, orders)

# returning everything from the left table. retain everything in the customers data

# We can exclude the "customer_ID" argument.

```

```{r}

right_join(customers, orders)

# left or right join, is just saying from which table do you want to keep everything in the argument.

```

```{r}

full_join(customers, orders)

# returns everything from both tables and matches where possible.

```

```{r}
customer_adj <- customers %>%
  rename(this_is_an_ID = customer_ID)

customer_adj

inner_join(customer_adj, orders, by = c("this_is_an_ID" = "customer_ID"))

# Adding this argument allows you to specify.

```

```{r}
# create a new column in both tables
customers2 <- customers %>%
  mutate(payment_type = c("card", "cash", "cash", "card", "card", "card"))

orders2 <- orders %>%
  mutate(payment_type = c("card", "cash", "cash", "card", "card", "cash"))

# join by two columns
inner_join(customers2, orders2, by = c("customer_ID", "payment_type"))
```

