---
title: "Scales and Coordinates"
author: "Jonny Nelson"
date: "30/11/2021"
output: html_document
---

```{r}
library(tidyverse)

pets <- read_csv("data/pets.csv")

ggplot(pets) +
  aes(age, weight, colour = sex) +
  geom_point() +
  scale_x_continuous(breaks = 1:13) +# adjust breaks here
  scale_y_continuous(breaks = c(5,7,9,11))
```

# Scales Limits

```{r}
ggplot(pets) +
  aes(age, weight, colour = sex) +
  geom_point() +
  scale_x_continuous(
    breaks = 1:13,
    limits = c(1, 8)
  ) +
  scale_y_continuous(
    breaks = c(6,8,10),
    limits = c(NA, 8)
  )
```

```{r}
ggplot(pets) +
  aes(age, weight, colour = sex) +
  geom_point() +
  xlim(1, 8) 
```

# Flipping a Plot

```{r}
ggplot(pets) +
  aes(x = animal, fill = sex) +
  geom_bar() 
```

```{r}
ggplot(pets) +
  aes(x = animal, fill = sex) +
  geom_bar() +
  coord_flip()
```

# Formatting Labels

```{r}
monthly_sales <- read_csv("data/monthly_sales.csv")

monthly_sales <- monthly_sales %>%
  mutate(month = factor(month, levels = c("Jan", "Feb", "March", "April"))) 

ggplot(monthly_sales) +
  aes(x = branch, y = sales, fill = month) +
  geom_col(position = "dodge") +
  coord_flip()
```

```{r}
monthly_sales %>%
  mutate(sales_thousands = sales/1000) %>%
ggplot() +
  aes(x = branch, y = sales_thousands, fill = month) +
  geom_col(position = "dodge") +
  ylab("Sales (1000's)") +
  coord_flip()
```

```{r}
ggplot(monthly_sales) +
  aes(x = branch, y = sales, fill = month) +
  geom_col(position = "dodge") +
  scale_y_continuous(labels = scales::comma) +
  coord_flip()
```

